name: mister
description: An app to give more visibility to self-employed professionals.

publish_to: "none"

version: 1.0.1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  mobx: ^2.0.5
  flutter_mobx: ^2.0.2
  get_it: ^7.2.0
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  google_sign_in: ^6.1.5
  firebase_database: ^10.2.5
  firebase_storage: ^11.2.6
  image_picker: ^1.0.4
  image_cropper: ^4.0.1
  shared_preferences: ^2.0.11
  font_awesome_flutter: ^10.5.0
  url_launcher: ^6.0.17

dev_dependencies:
  flutter_lints: ^2.0.3
  mobx_codegen: ^2.0.4
  build_runner: ^2.1.7
  flutter_config: ^2.0.0

flutter:
  uses-material-design: true
