name: mister
description: An app to give more visibility to self-employed professionals.

publish_to: "none"

version: 1.0.1

environment:
  sdk: ">=2.15.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  mobx: ^2.0.5
  flutter_mobx: ^2.0.2
  get_it: ^7.2.0
  firebase_core: ^1.11.0
  firebase_auth: ^3.3.5
  google_sign_in: ^5.2.1
  firebase_database: ^8.2.0
  firebase_storage: ^10.2.5
  image_picker: ^0.8.4+4
  image_cropper: ^1.4.1
  shared_preferences: ^2.0.11
  font_awesome_flutter: ^9.2.0
  url_launcher: ^6.0.17

dev_dependencies:
  flutter_lints: ^1.0.0
  mobx_codegen: ^2.0.4
  build_runner: ^2.1.7
  flutter_config: ^2.0.0

flutter:
  uses-material-design: true
